export const edicoes = [
    {
        id: 1,
        ano: "2010",
        img: "",
        divText: "Multimodalidade e intermodalidade",
        titulo: "I FATECLOG JUNDIAÍ",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 2,
        ano: "2011",
        img: "",
        divText: "",
        titulo: "II FATECLOG - FATEC JAHU",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 3,
        ano: "2012",
        img: "",
        divText: "",
        titulo: "FATECLOG - FATEC GUARATINGUET",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 4,
        ano: "2013",
        img: "",
        divText: "Gestão de produção",
        titulo: "IV FATECLOG - FATEC JAHU",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 5,
        ano: "2014",
        img: "",
        divText: "",
        titulo: "V FATECLOG - FATEC SJC",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 6,
        ano: "2015",
        img: "",
        divText: "",
        titulo: "VI FATECLOG - FATEC SOROCABA",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 7,
        ano: "2016",
        img: "",
        divText: "",
        titulo: "VII FATECLOG - FATEC AMERICANA",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 8,
        ano: "2017",
        img: "",
        divText: "Gestão de operações & logística urbana",
        titulo: "VIII FATECLOG - FATEC ZONA LESTE",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 9,
        ano: "2018",
        img: "",
        divText: "O papel do gestor de logística internaciona",
        titulo: "IX FATECLOG - FATEC BAIXADA SANTISTA",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 10,
        ano: "2019",
        img: "",
        divText: "Logistica 4.0 A sociedade do conhecimento",
        titulo: "X FATECLOG - FATEC GUARULHOS",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 11,
        ano: "2020",
        img: "",
        divText: "Os desafios da logística real no universo virtual",
        titulo: "XI FATECLOG - FATEC BRAGANÇA PAULISTA",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 12,
        ano: "2021",
        img: "",
        divText: "Gestão da cadeia de suprimentos no agronegócio: desafios e oportunidades no contexto atual",
        titulo: "XII FATECLOG - FATEC MOGI DAS CRUZES",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 13,
        ano: "2022",
        img: "",
        divText: "Os impactos das demandas pós - pandemia, nos sistemas logísticos das organizações.",
        titulo: "XIII FATECLOG - FATEC MAUÁ",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 14,
        ano: "2023",
        img: "",
        divText: "Logística e sociedade - Presença feminina, diversidade, inclusão social e sustentabilidade",
        titulo: "XIV FATECLOG - FATEC AMERICANA",
        linkAnais: "",
        linkCertificado: "",
    },
    {
        id: 15,
        ano: "2014",
        img: "",
        divText: "",
        titulo: "XV FATECLOG - FATEC JUNDIAÍ",
        linkAnais: "",
        linkCertificado: "",
    },
];


//modelo
// {
//     id: 0,
//     ano: "",
//     img: "",
//     divText: "",
//     titulo: "",
//     link: "",
// },